"""Local image collection helpers for audit inputs and MinerU artifacts."""

import os
import re
from pathlib import Path
from typing import Iterable, List

from .file_utils import _safe_name
from .namespace_utils import namespace_value as _namespace_value

DEFAULT_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".bmp", ".gif", ".tiff", ".tif", ".webp"}
DEFAULT_MIN_IMAGE_BYTES = 5000

__all__ = [
    "DEFAULT_IMAGE_EXTENSIONS",
    "DEFAULT_MIN_IMAGE_BYTES",
    "_dedupe_paths",
    "_image_output_dir",
    "_extract_images_from_mineru_zip",
    "_extract_images_from_mineru_zip_from_namespace",
    "extract_images_from_pdf",
    "collect_image_files_from_namespace",
    "collect_mineru_image_files",
    "collect_mineru_image_files_from_namespace",
    "_latest_mineru_zips",
]


def _dedupe_paths(paths: Iterable) -> List[str]:
    seen = set()
    result = []
    for path in paths:
        try:
            resolved = str(Path(path).resolve())
        except Exception:
            resolved = str(path)
        if resolved not in seen:
            seen.add(resolved)
            result.append(resolved)
    return result


def _image_output_dir(input_path: str):
    p = Path(input_path)
    if p.is_file():
        return p.parent / "_paper_audit_images"
    return p / "_paper_audit_images"


def _extract_images_from_mineru_zip(
    zip_path: Path,
    output_dir: Path,
    image_extensions=None,
    min_image_bytes=DEFAULT_MIN_IMAGE_BYTES,
) -> List[str]:
    images = []
    extensions = set(image_extensions or DEFAULT_IMAGE_EXTENSIONS)
    try:
        import zipfile

        output_dir.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(zip_path) as zf:
            for name in zf.namelist():
                suffix = Path(name).suffix.lower()
                if suffix not in extensions:
                    continue
                info = zf.getinfo(name)
                if info.file_size < min_image_bytes:
                    continue
                out_name = f"{_safe_name(zip_path.stem)}_{_safe_name(Path(name).stem)}{suffix}"
                out_path = output_dir / out_name
                out_path.write_bytes(zf.read(name))
                images.append(str(out_path))
    except Exception as e:
        print(f"  ⚠️ MinerU图片提取失败 {zip_path}: {e}")
    return images


def _extract_images_from_mineru_zip_from_namespace(namespace, zip_path: Path, output_dir: Path) -> List[str]:
    return _extract_images_from_mineru_zip(
        zip_path,
        output_dir,
        image_extensions=_namespace_value(namespace, "IMAGE_EXTENSIONS", DEFAULT_IMAGE_EXTENSIONS),
        min_image_bytes=_namespace_value(namespace, "MIN_IMAGE_BYTES", DEFAULT_MIN_IMAGE_BYTES),
    )


def collect_mineru_image_files(
    input_path: str,
    output_dir=None,
    image_extensions=None,
    min_image_bytes=DEFAULT_MIN_IMAGE_BYTES,
) -> List[str]:
    """Collect images saved inside MinerU zip artifacts generated by extraction."""
    extensions = set(image_extensions or DEFAULT_IMAGE_EXTENSIONS)
    p = Path(input_path)
    base = Path(output_dir) if output_dir else (p.parent if p.is_file() else p)
    zips = []
    if base.exists():
        zips.extend(base.glob("*.mineru.zip"))
    if p.is_dir():
        zips.extend(p.rglob("*.mineru.zip"))
    zips = _latest_mineru_zips(zips)
    images_dir = _image_output_dir(str(p))
    images = []
    for zip_path in _dedupe_paths(zips):
        images.extend(
            _extract_images_from_mineru_zip(
                Path(zip_path),
                images_dir,
                image_extensions=extensions,
                min_image_bytes=min_image_bytes,
            )
        )
    if zips:
        return _dedupe_paths(images)
    if images_dir.exists():
        for ext in extensions:
            for image_path in images_dir.rglob(f"*{ext}"):
                try:
                    if image_path.stat().st_size >= min_image_bytes:
                        images.append(str(image_path))
                except Exception:
                    continue
    return _dedupe_paths(images)


def collect_mineru_image_files_from_namespace(namespace, input_path: str, output_dir=None) -> List[str]:
    return collect_mineru_image_files(
        input_path,
        output_dir=output_dir,
        image_extensions=_namespace_value(namespace, "IMAGE_EXTENSIONS", DEFAULT_IMAGE_EXTENSIONS),
        min_image_bytes=_namespace_value(namespace, "MIN_IMAGE_BYTES", DEFAULT_MIN_IMAGE_BYTES),
    )


def extract_images_from_pdf(pdf_path: str) -> List[str]:
    """Extract embedded or rendered images from a PDF into a temporary folder."""
    images = []
    tmp_dir = os.path.join(os.path.dirname(pdf_path), "_veritas_images_tmp")
    os.makedirs(tmp_dir, exist_ok=True)

    try:
        import fitz  # PyMuPDF
        doc = fitz.open(pdf_path)
        img_count = 0
        for page_idx in range(len(doc)):
            page = doc[page_idx]
            img_list = page.get_images(full=True)
            for img_idx, img_info in enumerate(img_list):
                xref = img_info[0]
                try:
                    base_image = doc.extract_image(xref)
                    if base_image and base_image.get("image"):
                        ext = base_image.get("ext", "png")
                        if ext not in ("png", "jpg", "jpeg", "bmp", "tiff", "webp"):
                            ext = "png"
                        fname = f"page{page_idx + 1}_img{img_idx + 1}.{ext}"
                        fpath = os.path.join(tmp_dir, fname)
                        with open(fpath, "wb") as f:
                            f.write(base_image["image"])
                        if os.path.getsize(fpath) > 5000:
                            images.append(fpath)
                            img_count += 1
                except Exception:
                    continue
        doc.close()
        if img_count > 0:
            print(f"  📎 PyMuPDF提取 {img_count} 张内嵌图片 → {tmp_dir}")
            return images
    except ImportError:
        pass
    except Exception as e:
        print(f"  ⚠️ PyMuPDF提取失败: {e}")

    try:
        from pdf2image import convert_from_path
        pages = convert_from_path(pdf_path, dpi=200)
        for i, page_img in enumerate(pages):
            fname = f"page{i + 1}_full.png"
            fpath = os.path.join(tmp_dir, fname)
            page_img.save(fpath, "PNG")
            if os.path.getsize(fpath) > 10000:
                images.append(fpath)
        if images:
            print(f"  📎 pdf2image渲染 {len(images)} 页 → {tmp_dir}")
            return images
    except ImportError:
        pass
    except Exception as e:
        print(f"  ⚠️ pdf2image渲染失败: {e}")

    return images


def collect_image_files_from_namespace(namespace, input_path: str, include_pdf=True, include_mineru=True, output_dir=None) -> List[str]:
    """Collect local paper-related image files from directories, PDFs, and MinerU artifacts."""
    images = []
    p = Path(input_path)
    extensions = set(_namespace_value(namespace, "IMAGE_EXTENSIONS", DEFAULT_IMAGE_EXTENSIONS))
    min_image_bytes = _namespace_value(namespace, "MIN_IMAGE_BYTES", DEFAULT_MIN_IMAGE_BYTES)
    mineru_collector = _namespace_value(namespace, "collect_mineru_image_files", collect_mineru_image_files)
    pdf_extractor = _namespace_value(namespace, "extract_images_from_pdf", extract_images_from_pdf)

    if include_mineru:
        images.extend(mineru_collector(input_path, output_dir=output_dir))

    if include_pdf and p.is_file() and p.suffix.lower() == ".pdf":
        print("  📸 从PDF中提取图片...")
        images.extend(pdf_extractor(str(p)))
    elif p.is_dir():
        for ext in extensions:
            for image_path in p.rglob(f"*{ext}"):
                if ".paper_audit_resume" in str(image_path) or "_paper_audit_images" in str(image_path):
                    continue
                if image_path.stat().st_size > min_image_bytes:
                    images.append(str(image_path))

    return _dedupe_paths(images)


def _latest_mineru_zips(paths):
    latest = {}
    for path in paths:
        p = Path(path)
        name = p.name
        if not name.endswith(".mineru.zip"):
            continue
        key = name[: -len(".mineru.zip")]
        key = re.sub(r"\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", "", key, flags=re.I)
        try:
            mtime = p.stat().st_mtime
        except Exception:
            mtime = 0
        current = latest.get(key)
        if current is None or mtime > current[0]:
            latest[key] = (mtime, str(p))
    return [item[1] for item in latest.values()]
